#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
export ROOT="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

SCRSUFFIX="_lts.x"
NODENAME="Node.js 16.x"
NODEREPO="node_16.x"
NODEPKG="nodejs"
DISTRO=""

install_pkgs() {
    sudo apt-get update
    sudo apt-get install -y \
        apt-transport-https \
        lsb-release \
        gnupg \
        quilt \
        acl \
        aptly \
        aria2 \
        bc \
        binfmt-support \
        bison \
        btrfs-progs \
        build-essential \
        ca-certificates \
        ccache \
        cpio \
        cryptsetup \
        curl \
        zerofree \
        xxd \
        debian-archive-keyring \
        debian-keyring \
        debootstrap \
        device-tree-compiler \
        dialog \
        dirmngr \
        dosfstools \
        dwarves \
        f2fs-tools \
        fakeroot \
        flex \
        gawk \
        grep \
        curl \
        gcc \
        g++ \
        make \
        git \
        gcc-arm-linux-gnueabihf \
        gdisk \
        gnupg1 \
        gpg \
        imagemagick \
        jq \
        kmod \
        libbison-dev \
        libc6-dev-armhf-cross \
        libelf-dev libfdt-dev \
        libfile-fcntllock-perl \
        rsync \
        libfl-dev \
        liblz4-tool \
        libncurses-dev \
        libpython2.7-dev \
        libssl-dev \
        file \
        bc \
        libusb-1.0-0-dev \
        linux-base \
        locales \
        lzop \
        ncurses-base \
        ncurses-term \
        nfs-kernel-server \
        ntpdate \
        p7zip-full \
        parted \
        patchutils \
        pigz \
        pixz \
        pkg-config \
        pv \
        python3-dev \
        python3-distutils \
        qemu-user-static \
        rsync \
        swig \
        systemd-container \
        u-boot-tools \
        udev \
        unzip \
        uuid-dev \
        wget \
        whiptail \
        zip \
        zlib1g-dev \
        coreutils \
        qemu-user-static \
        kpartx \
        dosfstools \
        libcap2-bin \
        libarchive-tools \
        kmod \
        qemu-utils
}

check_alt() {
    if [ "X${DISTRO}" == "X${2}" ]; then
        DISTRO="${4}"
    fi
}

setup_nodesource() {
    DISTRO=$(lsb_release -c -s)

    check_alt "SolydXK" "solydxk-9" "Debian" "stretch"
    check_alt "Kali" "sana" "Debian" "jessie"
    check_alt "Kali" "kali-rolling" "Debian" "bullseye"
    check_alt "Sparky Linux" "Tyche" "Debian" "stretch"
    check_alt "Sparky Linux" "Nibiru" "Debian" "buster"
    check_alt "Sparky Linux" "Po-Tolo" "Debian" "bullseye"
    check_alt "MX Linux 17" "Horizon" "Debian" "stretch"
    check_alt "MX Linux 18" "Continuum" "Debian" "stretch"
    check_alt "MX Linux 19" "patito feo" "Debian" "buster"
    check_alt "MX Linux 21" "wildflower" "Debian" "bullseye"
    check_alt "Linux Mint" "maya" "Ubuntu" "precise"
    check_alt "Linux Mint" "qiana" "Ubuntu" "trusty"
    check_alt "Linux Mint" "rafaela" "Ubuntu" "trusty"
    check_alt "Linux Mint" "rebecca" "Ubuntu" "trusty"
    check_alt "Linux Mint" "rosa" "Ubuntu" "trusty"
    check_alt "Linux Mint" "sarah" "Ubuntu" "xenial"
    check_alt "Linux Mint" "serena" "Ubuntu" "xenial"
    check_alt "Linux Mint" "sonya" "Ubuntu" "xenial"
    check_alt "Linux Mint" "sylvia" "Ubuntu" "xenial"
    check_alt "Linux Mint" "tara" "Ubuntu" "bionic"
    check_alt "Linux Mint" "tessa" "Ubuntu" "bionic"
    check_alt "Linux Mint" "tina" "Ubuntu" "bionic"
    check_alt "Linux Mint" "tricia" "Ubuntu" "bionic"
    check_alt "Linux Mint" "ulyana" "Ubuntu" "focal"
    check_alt "Linux Mint" "ulyssa" "Ubuntu" "focal"
    check_alt "Linux Mint" "uma" "Ubuntu" "focal"
    check_alt "Linux Mint" "una" "Ubuntu" "focal"
    check_alt "LMDE" "betsy" "Debian" "jessie"
    check_alt "LMDE" "cindy" "Debian" "stretch"
    check_alt "LMDE" "debbie" "Debian" "buster"
    check_alt "elementaryOS" "luna" "Ubuntu" "precise"
    check_alt "elementaryOS" "freya" "Ubuntu" "trusty"
    check_alt "elementaryOS" "loki" "Ubuntu" "xenial"
    check_alt "elementaryOS" "juno" "Ubuntu" "bionic"
    check_alt "elementaryOS" "hera" "Ubuntu" "bionic"
    check_alt "elementaryOS" "odin" "Ubuntu" "focal"
    check_alt "elementaryOS" "jolnir" "Ubuntu" "focal"
    check_alt "Trisquel" "toutatis" "Ubuntu" "precise"
    check_alt "Trisquel" "belenos" "Ubuntu" "trusty"
    check_alt "Trisquel" "flidas" "Ubuntu" "xenial"
    check_alt "Trisquel" "etiona" "Ubuntu" "bionic"
    check_alt "Uruk GNU/Linux" "lugalbanda" "Ubuntu" "xenial"
    check_alt "BOSS" "anokha" "Debian" "wheezy"
    check_alt "BOSS" "anoop" "Debian" "jessie"
    check_alt "BOSS" "drishti" "Debian" "stretch"
    check_alt "BOSS" "unnati" "Debian" "buster"
    check_alt "bunsenlabs" "bunsen-hydrogen" "Debian" "jessie"
    check_alt "bunsenlabs" "helium" "Debian" "stretch"
    check_alt "bunsenlabs" "lithium" "Debian" "buster"
    check_alt "Tanglu" "chromodoris" "Debian" "jessie"
    check_alt "PureOS" "green" "Debian" "sid"
    check_alt "PureOS" "amber" "Debian" "buster"
    check_alt "PureOS" "byzantium" "Debian" "bullseye"
    check_alt "Devuan" "jessie" "Debian" "jessie"
    check_alt "Devuan" "ascii" "Debian" "stretch"
    check_alt "Devuan" "beowulf" "Debian" "buster"
    check_alt "Devuan" "chimaera" "Debian" "bullseye"
    check_alt "Devuan" "ceres" "Debian" "sid"
    check_alt "Deepin" "panda" "Debian" "sid"
    check_alt "Deepin" "unstable" "Debian" "sid"
    check_alt "Deepin" "stable" "Debian" "buster"
    check_alt "Pardus" "onyedi" "Debian" "stretch"
    check_alt "Liquid Lemur" "lemur-3" "Debian" "stretch"
    check_alt "Astra Linux" "orel" "Debian" "stretch"
    check_alt "Ubilinux" "dolcetto" "Debian" "stretch"

    sudo bash -c "curl -sLf -o /dev/null 'https://deb.nodesource.com/${NODEREPO}/dists/${DISTRO}/Release'"
    RC=$?

    if [[ $RC != 0 ]]; then
        echo "distribution \"${DISTRO}\", is not currently supported"
        exit 1
    fi

    if [ -f "/etc/apt/sources.list.d/chris-lea-node_js-$DISTRO.list" ]; then
        sudo bash -c "add-apt-repository -y -r ppa:chris-lea/node.js"
        sudo bash -c "rm -f /etc/apt/sources.list.d/chris-lea-node_js-${DISTRO}.list"
    fi

    keyring="/usr/share/keyrings"
    node_key_url="https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    local_node_key="$keyring/nodesource.gpg"

    sudo bash -c "curl -s $node_key_url | gpg --dearmor | tee $local_node_key >/dev/null"
    sudo bash -c "echo 'deb [signed-by=$local_node_key] https://deb.nodesource.com/${NODEREPO} ${DISTRO} main' > /etc/apt/sources.list.d/nodesource.list"
    sudo bash -c "echo 'deb-src [signed-by=$local_node_key] https://deb.nodesource.com/${NODEREPO} ${DISTRO} main' >> /etc/apt/sources.list.d/nodesource.list"
}

install_node() {
    sudo apt-get update
    sudo apt-get install -y nodejs
}

node_globals() {
    sudo npm install -g \
        npm \
        corepack
}

case $1 in
    increment )
        PROJECT=${2?Error: No Project specified}
        VERSION=${3?Error: Pass new version}

        echo "Updating ${PROJECT} to ${VERSION}"

        case $PROJECT in 
            image )
                (cd ./image && sudo ./project increment $VERSION)
                ;;

            kiosk )
                (cd ./kiosk && sudo ./project increment $VERSION)
                ;;
            
            portal )
                (cd ./portal && sudo ./project increment $VERSION)
                ;;
            
            cockpit )
                (cd ./cockpit && sudo ./project increment $VERSION)
                ;;

            nvr )
                (cd ./nvr && sudo ./project increment $VERSION)
                ;;
            
            all )
                echo "image"
                (cd ./image && sudo ./project increment $VERSION)
                echo "kiosk"
                (cd ./kiosk && sudo ./project increment $VERSION)
                echo "portal"
                (cd ./portal && sudo ./project increment $VERSION)
                echo "cockpit"
                (cd ./cockpit && sudo ./project increment $VERSION)
                echo "nvr"
                (cd ./nvr && sudo ./project increment $VERSION)
                ;;
        esac

        ;;

    build )
        shift

        if [ ! -d ./image/node_modules ]; then
            echo "project not setup, please run ./project setup"
            exit 1
        fi

        (cd ./image && sudo ./project build $@)
        ;;

    boards )
        (cd ./image && sudo ./project boards)
        ;;

    setup )
        install_pkgs
        setup_nodesource
        install_node
        node_globals

        (cd ./image && npm_config_loglevel=silent npm install --no-audit)
        (cd ./portal && npm_config_loglevel=silent npm install --no-audit)
        (cd ./cockpit && npm_config_loglevel=silent npm install --no-audit)
        (cd ./nvr && npm_config_loglevel=silent npm install --no-audit)
        (cd ./kiosk && npm_config_loglevel=silent npm install --no-audit)
        ;;

    clean )
        (cd ./image && sudo ./project clean)
        (cd ./portal && sudo ./project clean)
        (cd ./cockpit && sudo ./project clean)
        (cd ./nvr && sudo ./project clean)
        (cd ./kiosk && sudo ./project clean)
        ;;
esac
