#!/bin/bash

IP=$(hostname -I)

printf "To access this device, you can use SSH from another device on your network:" | fold -s
printf "\n\n"

for ip in $IP; do
  if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    printf "  http://$ip\n"
  else
    printf "  http://[$ip]\n"
  fi
done
