#!/bin/bash

export ROOT="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

if [[ "${EUID}" == "0" ]] || [[ "${1}" == "vagrant" ]]; then
	:
else
	echo "This script requires root privileges, trying to use sudo"

	sudo "${ROOT}/project" "$@"
	exit $?
fi

version() {
    echo `node -e 'console.log(require("./package.json").version)'`
}

case $1 in
    version ) 
        version
        ;;

    increment )
        CURRENT_VERSION=$(version)
        echo "Current Version: ${CURRENT_VERSION}"

        NEW_VERSION=${2?Error: Pass new version}
        echo "New Version: ${NEW_VERSION}"

        sed -i "s/\"version\": \"${CURRENT_VERSION}\"/\"version\": \"${NEW_VERSION}\"/" package.json
        sed -i "s/const version = \"${CURRENT_VERSION}\"/const version = \"${NEW_VERSION}\"/" ./lib/controllers/encompass.js
        ;;

    debug )
        rm -fR ./interface/*

        ./node_modules/.bin/vue-cli-service build --modern
        ./debug start -p 5500 -d
        ;;

    build )
        make nvr
        ;;

    clean )
        rm -fR ./dist
        rm -fR ./builds
        rm -fR ./node_modules
        ;;
esac
