# Rockchip RK3399 hexa core 4GB RAM SoC GBE eMMC USB3 USB-C WiFi/BT
BOARD_NAME="OrangePi 4 LTS"
BOARDFAMILY="rk3399"
BOOTCONFIG="orangepi-rk3399_defconfig"
KERNEL_TARGET="legacy,current,edge"
ASOUND_STATE="asound.state.rt5651"
BOOT_METHOD="uboot"