#!/bin/bash

export ROOT="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

if [[ "${EUID}" == "0" ]] || [[ "${1}" == "vagrant" ]]; then
	:
else
	echo "This script requires root privileges, trying to use sudo"

	sudo "${ROOT}/project" "$@"
	exit $?
fi

version() {
    echo `node -e 'console.log(require("./package.json").version)'`
}

debug() {
    rm -fR ./interface/*

    ./node_modules/.bin/vue-cli-service build --modern
    ./debug start -p 5000 -d
}

case $1 in
    version ) 
        version
        ;;

    debug )
        debug
        ;;

    build )
        make cockpit
        ;;

    clean )
        rm -fR ./dist
        rm -fR ./builds
        rm -fR ./interface
        rm -fR ./node_modules
        ;;
esac
