#!/bin/bash

version() {
	case $1 in
		armbian )
			echo `node -e 'console.log(require("./package.json").engines.armbian)'`
			;;

		nodesource )
			echo `node -e 'console.log(require("./package.json").engines.nodesource)'`
			;;

		node )
			echo `node -e 'console.log(require("./package.json").engines.node)'`
			;;

		* )
			echo `node -e 'console.log(require("./package.json").version)'`
			;;
	esac
}

case $1 in
	version )
		shift
		version $@
		;;

	boards )
		for board in config/boards/*.conf; do
			printf "$(head -2 "${board}" | tail -1 | sed 's/export //' | sed 's/BOARD_NAME="//' | sed 's/"//')\033[1;30m$(head -1 "${board}" | cut -d'#' -f2)\033[0m\n"
		done

		;;

	build )
		rm -f ./output/images/*

		NODE_REPO=$(version nodesource)
		VERSION=$(version)

		./compile "${VERSION}" NODE_REPO="${NODE_REPO}"

		mkdir -p ../builds
		cp ./output/images/* ../builds
		;;

	clean )
		sudo rm -fR ./.tmp
		sudo rm -fR ./atf
		sudo rm -fR ./output
		sudo rm -fR ./cache
		sudo rm -fR ./kernel
		sudo rm -fR ./misc
		sudo rm -fR ./overlay
		sudo rm -fR ./u-boot
		sudo rm -fR ./userpatches
		sudo rm -fR ./node_modules
		;;
esac
